// TRANSACTIONS
export const ADD_TRANSACTION ="ADD_TRANSACTION";
export const ADD_TRANSACTIONS ="ADD_TRANSACTIONS";
export const CLEAR_TRANSACTIONS ="CLEAR_TRANSACTIONS";

//ACCOUNTS
export const ADD_ACCOUNT ="ADD_ACCOUNT";
